import { createContext, useContext, useReducer, useCallback, useMemo, useEffect, useState, useRef } from 'react';
import { api } from '../api';

const CartCtx = createContext(null);

const uid = () => 'cart_' + Math.random().toString(36).slice(2, 9);

// Fresh state = one empty cart, active by default ("1st cart always active").
function initState() {
  const first = { id: uid(), label: 'Cart 1', items: [] };
  return { carts: [first], activeId: first.id, seq: 2 };
}

// Add/merge a product into an items array (single-cart logic, unchanged).
function addItem(items, p) {
  const existing = items.find((i) => i.id === p.id);
  if (existing) return items.map((i) => (i.id === p.id ? { ...i, qty: i.qty + 1 } : i));
  return [...items, { id: p.id, name: p.name, price: Number(p.price), image: p.image, qty: 1 }];
}

function reducer(state, action) {
  // Item actions apply to the ACTIVE cart only.
  const updateActive = (fn) => ({
    ...state,
    carts: state.carts.map((c) => (c.id === state.activeId ? { ...c, items: fn(c.items) } : c)),
  });

  switch (action.type) {
    case 'add':
      return updateActive((items) => addItem(items, action.product));
    case 'inc':
      return updateActive((items) => items.map((i) => (i.id === action.id ? { ...i, qty: i.qty + 1 } : i)));
    case 'dec':
      return updateActive((items) =>
        items.map((i) => (i.id === action.id ? { ...i, qty: i.qty - 1 } : i)).filter((i) => i.qty > 0)
      );
    case 'remove':
      return updateActive((items) => items.filter((i) => i.id !== action.id));
    case 'clear':
      return updateActive(() => []);

    // --- Cart session actions ---
    case 'newSession': {
      const c = { id: uid(), label: 'Cart ' + state.seq, items: [] };
      return { ...state, carts: [...state.carts, c], activeId: c.id, seq: state.seq + 1 };
    }
    case 'selectSession':
      return state.carts.some((c) => c.id === action.id) ? { ...state, activeId: action.id } : state;
    case 'resetSessions': // delete/clear ALL sessions -> back to a single empty cart
      return initState();

    case 'hydrate': {
      // Rehydrate from the DB. action.carts: [{ cart_id, items:[{id,name,price,image,qty}] }].
      // Labels are regenerated by order; the first cart becomes active.
      const carts = action.carts
        .filter((c) => c && c.cart_id)
        .map((c, idx) => ({ id: c.cart_id, label: 'Cart ' + (idx + 1), items: c.items || [] }));
      if (!carts.length) return state;
      return { carts, activeId: carts[0].id, seq: carts.length + 1 };
    }

    default:
      return state;
  }
}

export function CartProvider({ children }) {
  const [state, dispatch] = useReducer(reducer, undefined, initState);
  const [loaded, setLoaded] = useState(false); // gate sync until the DB load finishes

  // Load persisted carts once on mount so they survive a page refresh.
  useEffect(() => {
    let alive = true;
    api
      .get('/carts')
      .then((carts) => {
        if (alive && Array.isArray(carts) && carts.length) dispatch({ type: 'hydrate', carts });
      })
      .catch((e) => console.error('cart load failed', e))
      .finally(() => alive && setLoaded(true));
    return () => {
      alive = false;
    };
  }, []);

  // Persist the whole cart state to the DB (debounced) whenever it changes.
  // Sync is a full DELETE+INSERT, so overlapping requests must never race: we
  // keep at most one PUT in flight and always send the latest state, re-running
  // once more if changes queued up while a sync was ongoing.
  const stateRef = useRef(state);
  stateRef.current = state;
  const syncingRef = useRef(false);
  const pendingRef = useRef(false);

  const doSync = useCallback(async () => {
    if (syncingRef.current) {
      pendingRef.current = true; // coalesce: sync again after the current one finishes
      return;
    }
    syncingRef.current = true;
    try {
      const s = stateRef.current;
      await api.put('/carts', {
        carts: s.carts.map((c) => ({
          cart_id: c.id,
          items: c.items.map((i) => ({ id: i.id, price: i.price, qty: i.qty })),
        })),
      });
    } catch (e) {
      console.error('cart sync failed', e);
    } finally {
      syncingRef.current = false;
      if (pendingRef.current) {
        pendingRef.current = false;
        doSync(); // flush the latest state that arrived mid-sync
      }
    }
  }, []);

  useEffect(() => {
    if (!loaded) return;
    const t = setTimeout(doSync, 400);
    return () => clearTimeout(t);
  }, [state, loaded, doSync]);

  const active = state.carts.find((c) => c.id === state.activeId) || state.carts[0];
  const items = active.items;

  // Active-cart operations (same names/signatures as before).
  const add = useCallback((product) => dispatch({ type: 'add', product }), []);
  const inc = useCallback((id) => dispatch({ type: 'inc', id }), []);
  const dec = useCallback((id) => dispatch({ type: 'dec', id }), []);
  const remove = useCallback((id) => dispatch({ type: 'remove', id }), []);
  const clear = useCallback(() => dispatch({ type: 'clear' }), []);

  // Session operations.
  const addSession = useCallback(() => dispatch({ type: 'newSession' }), []);
  const selectSession = useCallback((id) => dispatch({ type: 'selectSession', id }), []);
  const clearSessions = useCallback(() => dispatch({ type: 'resetSessions' }), []);

  const { total, count } = useMemo(
    () => ({
      total: items.reduce((s, i) => s + i.price * i.qty, 0),
      count: items.reduce((s, i) => s + i.qty, 0),
    }),
    [items]
  );

  // Lightweight summary for the tab strip (recomputes when any cart changes).
  const sessions = useMemo(
    () =>
      state.carts.map((c) => ({
        id: c.id,
        label: c.label,
        count: c.items.reduce((s, i) => s + i.qty, 0),
      })),
    [state.carts]
  );

  const value = useMemo(
    () => ({
      items, add, inc, dec, remove, clear, total, count,
      sessions, activeId: state.activeId, addSession, selectSession, clearSessions,
    }),
    [items, add, inc, dec, remove, clear, total, count, sessions, state.activeId, addSession, selectSession, clearSessions]
  );
  return <CartCtx.Provider value={value}>{children}</CartCtx.Provider>;
}

export const useCart = () => useContext(CartCtx);
